# Generated by Django 4.0.7 on 2023-01-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='def.jpg', null=True, upload_to='profile_picture'),
        ),
    ]
